version: "3"

includes:
  advanced:
    dir: ./advanced
    taskfile: ./advanced/Taskfile.yml
  basic:
    dir: ./basic
    taskfile: ./basic/Taskfile.yml

tasks:
  typecheck:
    deps:
      - task: basic:typecheck
      - task: advanced:typecheck
    desc: Typecheck examples
